name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_semantic_pull_request.yml@38cee3a37246e813c1813110f1b94d0b2ece6023 # v0.93.0
